# Generated by Django 4.0 on 2022-01-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horoscope', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=45)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='zodiak_sing',
            name='description',
            field=models.TextField(),
        ),
    ]
