# Generated by Django 4.0 on 2022-01-06 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horoscope', '0002_element_alter_zodiak_sing_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.SmallIntegerField()),
                ('day_from', models.SmallIntegerField()),
                ('day_to', models.SmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='zodiak_sing',
            name='calendar_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='zodiak_sing',
            name='element_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='element',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='zodiak_sing',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
