# Generated by Django 4.0 on 2022-01-08 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horoscope', '0003_calendar_zodiak_sing_calendar_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zodiak_sing',
            name='element_id',
        ),
        migrations.AddField(
            model_name='zodiak_sing',
            name='element',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='horoscope.element'),
        ),
    ]
