# Generated by Django 4.0 on 2022-01-08 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horoscope', '0004_remove_zodiak_sing_element_id_zodiak_sing_element'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='month',
        ),
        migrations.RemoveField(
            model_name='zodiak_sing',
            name='calendar_id',
        ),
        migrations.AddField(
            model_name='calendar',
            name='month_from',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='calendar',
            name='month_to',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='zodiak_sing',
            name='calendar',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='horoscope.calendar'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='day_from',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='day_to',
            field=models.SmallIntegerField(null=True),
        ),
    ]
