# Generated by Django 4.0 on 2022-01-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZodiakSing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=45, unique=True)),
                ('description', models.TextField(blank=True)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('element', models.CharField(max_length=45)),
            ],
        ),
    ]
