# Generated by Django 4.0.2 on 2022-04-03 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horoscope_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forecasts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='zodiaksing',
            name='forecast',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='horoscope_app.forecasts'),
        ),
    ]
