# Generated by Django 4.0 on 2022-01-26 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horoscope_app', '0002_zodiaksingtest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=45, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ZodiakSingTest',
        ),
        migrations.RemoveField(
            model_name='zodiaksing',
            name='element',
        ),
        migrations.AddField(
            model_name='zodiaksing',
            name='elements',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='horoscope_app.elements'),
        ),
    ]
