# Generated by Django 4.0.2 on 2022-04-03 07:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horoscope_app', '0002_forecasts_zodiaksing_forecast'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sing', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=5000, null=True)),
                ('date_create', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.RemoveField(
            model_name='zodiaksing',
            name='forecast',
        ),
        migrations.DeleteModel(
            name='Forecasts',
        ),
    ]
