# Generated by Django 4.0 on 2022-01-26 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horoscope_app', '0003_elements_delete_zodiaksingtest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zodiaksing',
            name='elements',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='horoscope_app.elements'),
        ),
    ]
