# Generated by Django 4.0.2 on 2022-02-17 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horoscope_app', '0004_alter_zodiaksing_elements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elements',
            name='description',
        ),
    ]
